security:
  oauth2:
    client:
      authorized-grant-types: authorization_code,refresh_token,password
      client-id: jpb-springboot-arqref-key
      client-secret: psw.-jpb@1298!
      scope: openid
      # one year
      access-token-validity-seconds: 31536000
    resource:
      jwt:
        key-pair:
          alias: jpb-springboot-arqref-key
          store-password: psw.-jpb@1298!
spring:
  application:
    name: JPB Spring Boot Reference Architecture
  cache:
    jcache:
      config: classpath:spring-jcache.xml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baseline-on-migrate: true
    enabled: true
    validate-on-migrate: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jpa:
    generate-ddl: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        cache:
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
          use_query_cache: true
          use_second_level_cache: true
        generate_statistics: true
        globally_quoted_identifiers: true
        javax:
          cache:
            missing_cache_strategy: create
            provider: org.ehcache.jsr107.EhcacheCachingProvider
            uri: classpath:hibernate-jcache.xml
        jdbc:
          batch_size: 50
        max_fetch_depth: 0
  mvc:
    locale: pt_BR
  profiles:
    active: @spring.boot.profile@
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
