server:
  port: 8080
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/jpb-base-architecture?useSSL=false
    username: root

facebook:
  appId:

google:
  appId:

app:
  url: http://localhost:8080
